[package]
name = "senso-rake"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
axum = "0.8.7"
duckdb = { version = "1.4.4", features = ["appender-arrow", "bundled", "vtab-arrow"] }
prometheus = "0.14.0"
rumqttc = "0.25.1"
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
http = "1.4"
chrono = { version = "0.4", features = ["serde"] }
crossbeam-channel = "0.5.15"
async-trait = "0.1.89"
ulid = "1.2.1"
sha2 = "0.10.9"
log = "0.4.29"
env_logger = "0.11.8"
arrow-json = "58"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
